<?php
function dashboard_menu(){
    $items = array();

    $items['dashboard'] = array(
        'title' => 'Dashboard',	
        'page callback' => 'dashboard_content',
        'access callback' => 'user_access',
        // 'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function dashboard_content() {
  // Done by Subham 20/06/2024 & 21/06/2024
  global $user;
  $query = db_select('housing_applicant_official_detail', 'haod');
  $query->innerJoin('housing_applicant', 'ha', 'ha.uid = haod.uid');
  $query->fields('ha', array('applicant_name','gender','mobile_no'));
  $query->fields('haod', array('applicant_designation'));
  $query->condition('ha.uid',$user->uid);
  $result =$query->execute();
  $result = $result->fetchAssoc();
  
  $output['user_info'] = $result;
  return theme('custom_dashboard_template', $output);
}

function dashboard_theme() {
    return array(
      'custom_dashboard_template' => array(
        'variables' => array($output),
        'template' => 'custom-dashboard-template',
      ),
    );
  }